#!/bin/bash -e


function jruby-install() {
  echo "Installing JRuby..."

  if [ "$OPENSHIFT_JRUBY_VERSION" == "" ]
  then
    OPENSHIFT_JRUBY_VERSION=`curl http://jruby.org/download | ruby -e "s=ARGF.read;x=/Current Release: JRuby (\d\.\d\.\d)/m.match(s);puts x[1]"`
  fi

  #if jruby in sandbox exists then copy, if not download

  #mkdir -p ${OPENSHIFT_JRUBY_DIR}versions
  #cd ${OPENSHIFT_JRUBY_DIR}versions

  pushd ${OPENSHIFT_RUBY_DIR}/../.sandbox 1>/dev/null

  curl -o jruby.tar.gz http://jruby.org.s3.amazonaws.com/downloads/$OPENSHIFT_JRUBY_VERSION/jruby-bin-$OPENSHIFT_JRUBY_VERSION.tar.gz

  tar xf jruby.tar.gz
  rm -rf jruby.tar.gz
}